title: "Seasonal Forecasting Book"
author: "Sabela Sanfiz"
logo: _static/logo.jpg  # logo AEMET

# Ejecuci贸n de notebooks 
execute:
  execute_notebooks: "cache"  

# Configuraci贸n de la interfaz del libro
html:
  use_issues_button: true
  use_repository_button: true
  use_edit_page_button: false
  extra_static_paths:
    - _static  # Se asegura de que _static/ se use correctamente
  extra_css:
    - _static/custom.css
  extra_navbar: _static/sidebar.html

# Habilitar extensiones para Markdown avanzado
sphinx:
  config:
    html_theme: sphinx_rtd_theme
    html_theme_options:
      sticky_navigation: True  # Mantener la navegaci贸n visible al hacer scroll
      navigation_with_keys: true  # Permite moverse con flechas en el libro

    myst_enable_extensions:
      - amsmath      
      - dollarmath   
      - colon_fence  
      - deflist      
      - html_image   



repository:
  url: https://github.com/Sanfiz/seasonal_book  
  path_to_book: docs 
  branch: master 

# Configuraci贸n de LaTeX
latex:
  latex_elements:
    preamble: |
      \usepackage{amsmath}  
      \usepackage{bm}       
      \usepackage{tcolorbox} 

